server: "hub.lambdatest.com"
user: "<YOUR LAMBDATEST USERNAME>"
key: "<YOUR LAMBDATEST KEY>"

common_caps:
  "build": "capybara-lambdatest"
  "name": "single-Test-Jenkins"

browser_caps:
  -
    "browserName": "chrome"
    "version": "64.0"
    "platform": "Windows 7"
    "video": true
    "network": false
    "console": false
    "visual": false
