server: "hub.lambdatest.com"
user: "qalambdatest"
key: "vz1efec4XUkJ0rtQrvXE6gLNa15N0K1D1wgnS2c0pJ5xt3E0vd"

common_caps:
  "build": "capybara-lambdatest"
  "name": "single-Test-Jenkins"

browser_caps:
  -
    "browserName": "chrome"
    "version": "64.0"
    "platform": "Windows 7"
    "video": true
    "network": true
    "console": true
    "visual": true
